FROM fedora:37

# Install required packages
RUN dnf update -y && \
    dnf upgrade -y && \
    dnf install -y curl \
    fish \
    flatpak-builder \
    git \
    kitty \
    python3 \
    pipx && \
    dnf clean all

# Install nvm (Node Version Manager)
ENV NVM_DIR=/root/.nvm

# Install the latest LTS (Long Term Support) version of Node.js and Yarn using nvm
# Source nvm.sh script to load nvm functions in the current shell session
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    source $NVM_DIR/nvm.sh && \
    nvm install --lts && \
    nvm use --lts && \
    npm install --global yarn

# Clone and install flatpak-builder-tools in the same RUN command to reduce layers
RUN git clone https://github.com/flatpak/flatpak-builder-tools && \
    cd flatpak-builder-tools/node/ && \
    pipx install .

# use kitty terminal emulator
ENV TERM=xterm-kitty

# Set PATH environment variable to include nvm binaries
ENV PATH=$PATH:$NVM_DIR/versions/node/"$(source $NVM_DIR/nvm.sh && nvm current)"/bin

# Create a working directory for building flatpaks
WORKDIR /logseq-flatpak

SHELL ["/bin/fish"]
ENTRYPOINT ["/bin/fish"]
